name: Build Binary
on: [push]
#on:
#  push:
#    branches:    
#      - master
jobs:
  version:
    name: Generate build number
    runs-on: macos-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    - name: Upload build number
      uses: actions/upload-artifact@v1
      with:
        name: BUILD_NUMBER
        path: BUILD_NUMBER

  build:
    name: Build
    needs: version
    runs-on: macos-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [arm, amd64, 386]
    steps:
    - name: Download build number
      uses: actions/download-artifact@v1
      with:
        name: BUILD_NUMBER
    - name: Restore build number
      id: buildnumber
      uses: einaregilsson/build-number@v1 

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build
      env: 
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
#        go tool dist install pkg/runtime
#        go install -a std
        go build -o build/emitter-${{ matrix.os }}-${{ matrix.arch }} -i -ldflags "-X github.com/emitter-io/emitter/internal/command/version.version=$BUILD_VERSION -X github.com/emitter-io/emitter/internal/command/version.commit=$GITHUB_SHA" .
