name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go install golang.org/x/tools/cmd/cover
        go install github.com/mattn/goveralls
        go install github.com/go-playground/overalls
        go get -v -t -d ./...

    - name: Run Tests
      run: |
        go test ./...
        overalls -project=github.com\emitter-io\emitter
        goveralls -coverprofile=overalls.coverprofile -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%

    - name: Build
      run: go build -v .